### ISSUE TITLE
Switch to "Awesome Styler" theme to enable settings

### ISSUE THREAD

**Issue by sdasda7777** [yoyurec/logseq-awesome-styler#109]
**Info:**
- OS: Windows
- Logseq ver: 0.10.3
- Plugin ver: Latest?

**Description:**
Hi, in the plugin settings, I get this: "Switch to "Awesome Styler" theme to enable settings". However, it is not clear to me what that means. In Logseq settings I have options "light", "dark" and "system", no "Awesome Styler". Is the plugin broken? Or is the message just not obvious enough for me?

**Screenshots**

![image](https://github.com/yoyurec/logseq-awesome-styler/assets/17746796/e14b0057-7344-471d-a95e-242c9298b656)

![image](https://github.com/yoyurec/logseq-awesome-styler/assets/17746796/07354b96-4ff8-40dd-8e24-fc90b84b9a73)

**Comment by yoyurec** [comment]
Logseq has Themes Switcher - in three dot menu
![image](https://github.com/yoyurec/logseq-awesome-styler/assets/137919/d604f2d7-f529-4d4a-b167-085b4671d873)

light/dark settings its not "theme", but rather "mode"

**Comment by sdasda7777** [comment]
Thanks, that's really confusing. Could you make the instructions bit more specific perhaps?
