### ISSUE TITLE
Right click don't open the contextual menu

### ISSUE THREAD

**Issue by bwnyasse** [yoyurec/logseq-awesome-styler#47]
**Info:**
- OS: Windows 10
- Logseq ver: 0.8.2
- Theme ver: v2.1.6
- ⚠  I don't have any custom info in ny custom.css
- ⚠  I don't have the bug using default theme

**Description:**
On windows, every time I press the right click on the mouse, nothing is happening.

**To Reproduce:**
- Install LogSeq on Windows
- Install solarized extended theme
- Press the right click of your mouse
- Nothing is happening ( Bug )

**Expected behavior:**
- Install LogSeq on Windows
- Install solarized extended theme
- Press the right click of your mouse
- The contextual menu must been shown ( expected behavior )

**Attach files**
Demo
![Logseq-2022-09-05-11-01-08](https://user-images.githubusercontent.com/5323628/188477780-c3bf92af-3022-4948-8ee6-02c68f876095.gif)

**Comment by yoyurec** [comment]
Win10, can't reproduce ((

**Comment by yoyurec** [comment]
is it stiil exist in latest SolExt and Logseq 0.8.7?

**Comment by yoyurec** [comment]
@bwnyasse does it still exist in latest AwesomeStyler & latest Logseq?

**Comment by yoyurec** [comment]
@bwnyasse does it still exist in latest AwesomeStyler+AwesomeUI & latest Logseq?
