### ISSUE TITLE
Important in css

### ISSUE THREAD

**Issue by oriofdarkforest** [yoyurec/logseq-awesome-styler#58]
This css used `!important` and make my custom css unavailable.
I don't think it's a good idea.
I have to add `!important` to all my custom css to make them work again.

**Comment by yoyurec** [comment]
yes, it touch a lot of things... as any theme
any suggestions to specific most pain rules to check possibility to delete?

**Comment by yoyurec** [comment]
in upcoming release i'll get rid of most of them
