### ISSUE TITLE
Provide Support for Custom Fonts

### ISSUE THREAD

**Issue by ianelletson** [yoyurec/logseq-awesome-styler#59]
**Idea**
Provide either a dialog for choosing a font or support for specifying a particular font via .css

I'd like to use Yrsa, a serif font, for text, and JetBrains Mono for code.

It looks like I could modify `awesomeStyler.css` to support my font choices but it seems fragile to do so.

**Comment by yoyurec** [comment]
i'm using fonts:
a) manually picked and only for predefined presets
b) fonts files downloaded locally for offline mode, so i cant support any font

> It looks like I could modify awesomeStyler.css to support my font choices but it seems fragile to do so

you can modify variables!
```css
.light-theme,
.dark-theme,
html[data-theme='light'],
html[data-theme='dark'] {
    --awSt-font-fira-code: "your font name", Monaco, Menlo, Consolas, "COURIER NEW", monospace;
    --awSt-code-font: "your font name", sans-serif; ;
}
```

OR there is already plugin for your needs - https://github.com/vipzhicheng/logseq-plugin-google-fonts
