### ISSUE TITLE
"Content max width" doesn't work

### ISSUE THREAD

**Issue by jimmy909090** [yoyurec/logseq-awesome-styler#60]
![image](https://user-images.githubusercontent.com/113656415/196306326-7382cc03-e6e4-4fe6-9c7e-65ba2e25bbe8.png)

**Comment by cleanclothes-pi** [comment]
Comfirm: I experience the same issue. 
I will also add that I tried override it with `custom.css` file and it does not work either (although I'm not sure if it's intentional for Awesome Styler to have priority over custom.css?).

**Comment by yoyurec** [comment]
>  if it's intentional for Awesome Styler to have priority over custom.css?

priority same as everywhere in web - CSS specifity https://web.dev/learn/css/specificity/

**Comment by yoyurec** [comment]
fixed in v3.1.1
