### ISSUE TITLE
Multi-color highlight support

### ISSUE THREAD

**Issue by kinalmehta** [yoyurec/logseq-awesome-styler#61]
Refer: https://github.com/DenaroCF/Highlighters-for-Logseq
The above plugin is not on the plugin marketplace, and it would be a nice addition to this styler theme with option to select colors in the configuration panel

Thanks

**Comment by yoyurec** [comment]
AwStyler for coloring default Logseq stuff...

\+ there is some exiting built-in coloring via the context menu
![image](https://user-images.githubusercontent.com/137919/198517919-e3a34657-458c-4a81-87c9-5863d8a23a6a.png)
