### ISSUE TITLE
Wrapped code blocks or syntax highlighting in single backtick code snippets

### ISSUE THREAD

**Issue by itsamemarkus** [yoyurec/logseq-awesome-styler#62]
**Idea**
I don't know if it's possible to do that as a theme or if it requires deeper logseq changes. But one thing I'd like to have is an option to wrap code blocks.

**Screenshots**
currently 
![image](https://user-images.githubusercontent.com/34944988/198824038-a345a692-3a1b-4f41-8060-911cb67bf5a1.png)

something like that, maybe with visual indicator that the line is wrapped
![image](https://user-images.githubusercontent.com/34944988/198823990-8ca77de0-5550-486d-81fa-ad8e68dddb21.png)

The main reason I'd like to see this is for large one line CLI commands like this one

![image](https://user-images.githubusercontent.com/34944988/198824191-e4d16c1f-7088-4582-aed3-96de13938a46.png)

Maybe another solution would be to have syntax highlighting enabled in single backtick `code snippets`

**Comment by yoyurec** [comment]
it's Logseq core things
but you can pass CodeMirror options in `config.edn`. Search lines:
```
 ;; Extra CodeMirror options
 ;; :editor/extra-codemirror-options {:keyMap "emacs" :lineWrapping true}
```
uncomment and set lineWrapping:
```
 ;; Extra CodeMirror options
 ;; :editor/extra-codemirror-options {:keyMap "emacs" :lineWrapping true}
:editor/extra-codemirror-options {:lineWrapping true}
```
