### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by cornelius-99** [yoyurec/logseq-awesome-styler#64]
**Info:**
- OS: macOS 12.6 (21G115)
- Logseq ver: 
- Plugin ver: v3.1.11
- [x] ⚠ Do i have issue with DISABLED my `custom.css`?
- [x] ⚠ Do i have the same on default theme?

**Description:**
Plugin completely infunctional

**To Reproduce:**
Install Plugin from Marketplace or load manually

**Expected behavior:**
Plugin should be configurable via settings

**Screenshots**
<img width="948" alt="image" src="https://user-images.githubusercontent.com/22989242/199469926-10c187ad-f5df-4624-afba-46a88e2ab7df.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/22989242/199470023-2c9e0dfe-4a07-44b3-a828-423414610976.png">
The only plugin that is activated! (Also listet under Plugins, not Themes)

**Attach files**

**Comment by yoyurec** [comment]
try to uninstall/install, reload Logseq...

> Plugin should be configurable via settings

only if you set the theme as active!
(there was a message in settings, but gone 😣, need to check)

![image](https://user-images.githubusercontent.com/137919/199471280-1c7e3f48-2f08-4c70-869b-2f8ff533b566.png)


> Also listet under Plugins, not Themes

it's not "theme" anymore ))

**Comment by yoyurec** [comment]
message fixed in 3.1.12
but again - the theme should be chosen!
in another case how you will see the customization effect? ))
