### ISSUE TITLE
Linebreak in Page Properties

### ISSUE THREAD

**Issue by Yavinah** [yoyurec/logseq-awesome-styler#65]
First of all, thank you for your great plugin/style! It makes my work much more fun. Thank you!

However, I noticed a "bug", if you can call it that. If I use page properties (e.g. type:: book) at the beginning of a page that goes over several lines, this is displayed normally in view mode. However, when I click into the property to edit it, a multi-line property on the right side of the Logseq window disappears and becomes a very long line, so I have to use a scrollbar to get to the end of the line (which disrupts my workflow as the scrollbar doesn't work perfectly). It would be much better if the line was also broken in edit mode, as it already is in view mode of page properties or queries (which is great!). 

Thanks for this! :)

**This is the unliked Scrollbar in Editing-Mode:**
![ScrollbarInEditingMode](https://user-images.githubusercontent.com/104633946/199690978-55444b41-ad39-4c23-a786-1473d8d949b6.png)

**This is the (perfect) Viewing Mode:**
![PerfectInViewingMode](https://user-images.githubusercontent.com/104633946/199690762-67b0f675-d96c-4ca4-b0fa-8a6a6e33c880.png)

**Comment by yoyurec** [comment]
yes, i know about it and this was made especially.
in edit mode icon is repeated background, not connected to each line... 
so when line is wrapped (for ex into 3 lines, like your example) then you will see 3 pen-edit icons (((((

![image](https://user-images.githubusercontent.com/137919/199868272-9e5b2589-475f-47db-8e8c-7f34b8c79b48.png)

and this looks buggy and annoing.
so solution is only 1 - delete "edit mode" styling, which i'm not resdy to do, due low % case of long props values
...at list now, when not so many ppl mentioned this as unacceptable issue.
