### ISSUE TITLE
Remove Page Shadow

### ISSUE THREAD

**Issue by cornelius-99** [yoyurec/logseq-awesome-styler#66]
**Idea**
In my opinion removing the shadow of the Page makes the UI look more "modern". By adding a checkbox in the Settings it could be disabled

**Screenshots**
This box-shadow style is what i mean:
![image](https://user-images.githubusercontent.com/22989242/199775256-e2ea1a6b-e4ac-45b7-900d-a156b07cd2e4.png)

With shadow:
![image](https://user-images.githubusercontent.com/22989242/199776009-3693ee85-533b-436d-8196-a191587ab12b.png)

Without shadow
![image](https://user-images.githubusercontent.com/22989242/199775768-2540ca56-6583-4056-bf8d-ae054353d571.png)

**Comment by cornelius-99** [comment]
Or if its reasonable you could disable the shadow when there is no background image specified. But that just an idea

**Comment by yoyurec** [comment]
are you sure the option does not exist? )

![image](https://user-images.githubusercontent.com/137919/199780663-9279e5f1-cd82-497e-96a2-fe79cb356c61.png)

**Comment by cornelius-99** [comment]
Oh well... I didn't saw that. Sry
