### ISSUE TITLE
How can I set customized font?

### ISSUE THREAD

**Issue by codingbylch** [yoyurec/logseq-awesome-styler#69]
**Idea**
How can I set customized font? such as [LxgwWenKai](https://github.com/lxgw/LxgwWenKai)

**Comment by yoyurec** [comment]
The current plugin has only a few handpicked fonts.
To use your own, you need to import it (font should be available via CDN) and apply it in `custom.css` 

Google how to do it via CSS or ask in Logseq Discord channel
