### ISSUE TITLE
Color code not being showed in setting panel.

### ISSUE THREAD

**Issue by CharlesChiuGit** [yoyurec/logseq-awesome-styler#72]
**Info:**
- OS: Win11
- Logseq ver: v0.8.12
- Plugin ver: v3.2.1
- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?
- [ ] ⚠ Do i have the same on default theme?

**Description:**
Color code not being showed in setting panel.
Also, I have remove every code in `custom.css` and `custom.js`.

**To Reproduce:**
Install plugin and open **awesome styler** setting panel.

**Expected behavior:**
Color code being showed in setting panel.

**Screenshots**
![圖片](https://user-images.githubusercontent.com/32497323/207956240-699e56c7-e9bf-4e16-8bee-97dd177cb3a1.png)

**Comment by yoyurec** [comment]
hm... sometimes it happens on slow computers - something wrong with color picker init timigs, will try to add bigger delay...

**Comment by yoyurec** [comment]
check latest v3.2.2

**Comment by CharlesChiuGit** [comment]
Still having same issue.

**Comment by yoyurec** [comment]
hmmm... (((
any errors in devtools console? `ctrl+shift+i`

**Comment by CharlesChiuGit** [comment]
I'm not sure which error to find, so below is every error log in console:
1.
![圖片](https://user-images.githubusercontent.com/32497323/214044639-5a9691b3-cd45-4e9c-98ce-9020ec77706e.png)
2.
![圖片](https://user-images.githubusercontent.com/32497323/214044668-7bdfb0c7-0e02-4189-bc75-04c3764bb907.png)
3.
![圖片](https://user-images.githubusercontent.com/32497323/214044726-1d0c4014-01ed-48aa-a672-4b7869d35e30.png)
4.
![圖片](https://user-images.githubusercontent.com/32497323/214044786-6ed30204-5c0c-42e0-930b-5510e5920930.png)

**Comment by yoyurec** [comment]
see no `awesomeStyler.xxxxxxxx.js` errors...

**Comment by CharlesChiuGit** [comment]
Never mind, since this plugin is too heavy for my pc. I will try other way to customize my logseq. thanks for your hard work.

**Comment by yoyurec** [comment]
why " too heavy"? ((

**Comment by CharlesChiuGit** [comment]
> hm... sometimes it happens on slow computers

b/c i have a slow computer?

**Comment by yoyurec** [comment]
> i have a slow computer

i don't know )) do you? )

**Comment by yoyurec** [comment]
looks like i got it...

> I found temporarily solution , I need to enter setting panel with different way.

temporary? Settings>Plugins>AwesomeStyler is the main way ))

or you are using Plugins>Gear icon>Open Settings all the time?

**Comment by CharlesChiuGit** [comment]
My pc spec: 
cpu: i5-6600K
ram: 16GB
running on SSD

Maybe not that fast.

**Comment by CharlesChiuGit** [comment]
That will be nice! 

> neither way won't work for some reason.

But I mean neither "Settings>Plugins>AwesomeStyler" nor "Plugins>Gear icon>Open Settings" shows the colored panel.

I had also tried to remove the `custom.js` and `custom.css` to see if there's something conflicting with Awesome styler, but nothing really changed after removing both files.

Here's the preview now:
![圖片](https://user-images.githubusercontent.com/32497323/214114363-41a782f5-470a-4676-aa61-16bbd8f1e959.png)
![圖片](https://user-images.githubusercontent.com/32497323/214114423-bb9d2247-3804-4bec-a158-b111bcbbed2b.png)

**Comment by yoyurec** [comment]
BTW, in "Settings>Plugins>AwesomeStyler" do you see disabled inputs/dropdowns (for ex. Font type, font size...) when a read-only preset is chosen (for ex. "Solarized_default")?

**Comment by yoyurec** [comment]
PM'ed you on Discord, chatting is faster )

**Comment by yoyurec** [comment]
check latest ver

**Comment by yoyurec** [comment]
"Plugins>Gear icon>Open Settings" now disabled for Styled due impossible to programmatically reload popup (needed after presets switching).

![image](https://user-images.githubusercontent.com/137919/214759117-dce9da03-299e-4546-a73c-df2d435b2f4d.png)

**Comment by yoyurec** [comment]
fixed in v3.2.5

**Comment by CharlesChiuGit** [comment]
It works! Thanks for your hard work!
