### ISSUE TITLE
light mode not compatable?

### ISSUE THREAD

**Issue by Conchilardo** [yoyurec/logseq-awesome-styler#74]
**Info:**
- OS: mac os 13.1 (22C65)
- Logseq ver: 0.8.16 (install through homebrew)
- Plugin ver: 3.2.6
- [no? ] ⚠ Do i have issue with DISABLED my `custom.css`?
- [ no?] ⚠ Do i have the same on default theme?

**Description:**
when in light mode no changes will be shown (just logseq standard light mode). No color changes, background etc. Also, when clicking on cells to change color values the color palate does not pop up. Everything functions as needed in dark mode

**Comment by yoyurec** [comment]
"Default" theme not chosen? "Awesome styler light" active?
![image](https://user-images.githubusercontent.com/137919/215360577-e8f24c51-e542-4e18-a7df-f05d00a42eca.png)

**Comment by yoyurec** [comment]
Try to reload Logseq (Cmd+R) or restart. Did it help?

**Comment by Conchilardo** [comment]
> "Default" theme not chosen? "Awesome styler light" active? ![image](https://user-images.githubusercontent.com/137919/215360577-e8f24c51-e542-4e18-a7df-f05d00a42eca.png)

it was indicated as selected. However I tried clicking on it and the page refreshed and is now working. Unsure as to why it was behaving in that way but for now it appears resolved.

Thank you for all your hard work btw. This is pretty sweet
