### ISSUE TITLE
The Graph View Page is a bit odd

### ISSUE THREAD

**Issue by iBeACoder** [yoyurec/logseq-awesome-styler#79]
The graph view page has an issue where it will show the background banner. This will then reduce the area of the graph and cut parts of it out.
![image](https://user-images.githubusercontent.com/19941071/218892583-f188b298-f638-493c-81ad-d530fa6cc01a.png)

It is usually zoomed in but the banner on the right will cut out half of the graph. And sometimes the banner will not load and it becomes very difficult to know why half of the screen is cut out.

It would be great to just disable the background images/banner for this one page. So the whole page is used for viewing the graph.

**Comment by yoyurec** [comment]
fixed in the latest release, check!

**Comment by iBeACoder** [comment]
Thank you so much!
