### ISSUE TITLE
Used with logseq-plugin-link-preview cause preview transparent background and weird font styles

### ISSUE THREAD

**Issue by sagiwei** [yoyurec/logseq-awesome-styler#83]
**Info:**
- OS: macOS 13.1
- Logseq ver: 0.8.18
- Plugin ver: 3.6.7
- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?
- [ ] ⚠ Do i have the same on default theme?

**Description:**
When [logseq-plugin-link-preview](https://github.com/pengx17/logseq-plugin-link-preview) and [logseq-awesome-styler](https://github.com/yoyurec/logseq-awesome-styler) both enabled, mouse over a link the preview card renders a the title and description with a transparent background, no borders and weird font styles. 
Same issue has been opened in `logseq-plugin-link-preview`: pengx17/logseq-plugin-link-preview#122

**To Reproduce:**
 Enable `logseq-plugin-link-preview` and `logseq-awesome-styler` at same time.

**Screenshots**
![](https://user-images.githubusercontent.com/13987735/210870656-83e53075-4531-48f9-a2d3-5befa77bd13d.png)

**Comment by yoyurec** [comment]
PR created https://github.com/pengx17/logseq-plugin-link-preview/pull/126
